enum ActionTypes {
  REQUEST_GET_SPACE = 'space/REQUEST_GET_SPACE',
  REQUEST_GET_SPACE_SUCCESS = 'space/REQUEST_GET_SPACE_SUCCESS',
  REQUEST_GET_SPACE_FAILURE = 'space/REQUEST_GET_SPACE_FAILURE',

  REQUEST_UPDATE_SPACE = 'space/REQUEST_UPDATE_SPACE',
  REQUEST_UPDATE_SPACE_SUCCESS = 'space/REQUEST_UPDATE_SPACE_SUCCESS',
  REQUEST_UPDATE_SPACE_FAILURE = 'space/REQUEST_UPDATE_SPACE_FAILURE',

  REQUEST_GET_BOOK = 'space/REQUEST_GET_BOOK',
  REQUEST_GET_BOOK_SUCCESS = 'space/REQUEST_GET_BOOK_SUCCESS',
  REQUEST_GET_BOOK_FAILURE = 'space/REQUEST_GET_BOOK_FAILURE',

  REQUEST_ADD_BOOK = 'space/REQUEST_ADD_BOOK',
  REQUEST_ADD_BOOK_SUCCESS = 'space/REQUEST_ADD_BOOK_SUCCESS',
  REQUEST_ADD_BOOK_FAILURE = 'space/REQUEST_ADD_BOOK_FAILURE',

  REQUEST_DELETE_BOOK = 'space/REQUEST_DELETE_BOOK',
  REQUEST_DELETE_BOOK_SUCCESS = 'space/REQUEST_DELETE_BOOK_SUCCESS',
  REQUEST_DELETE_BOOK_FAILURE = 'space/REQUEST_DELETE_BOOK_FAILURE',

  REQUEST_ADD_REVIEW = 'space/REQUEST_ADD_REVIEW',
  REQUEST_ADD_REVIEW_SUCCESS = 'space/REQUEST_ADD_REVIEW_SUCCESS',
  REQUEST_ADD_REVIEW_FAILURE = 'space/REQUEST_ADD_REVIEW_FAILURE',

  REQUEST_UPDATE_REVIEW = 'space/REQUEST_UPDATE_REVIEW',
  REQUEST_UPDATE_REVIEW_SUCCESS = 'space/REQUEST_UPDATE_REVIEW_SUCCESS',
  REQUEST_UPDATE_REVIEW_FAILURE = 'space/REQUEST_UPDATE_REVIEW_FAILURE',

  REQUEST_DELETE_REVIEW = 'space/REQUEST_DELETE_REVIEW',
  REQUEST_DELETE_REVIEW_SUCCESS = 'space/REQUEST_DELETE_REVIEW_SUCCESS',
  REQUEST_DELETE_REVIEW_FAILURE = 'space/REQUEST_DELETE_REVIEW_FAILURE',

  REQUEST_GET_ALL_REVIEW_COMMENTS = 'space/REQUEST_GET_ALL_REVIEW_COMMENTS',
  REQUEST_GET_ALL_REVIEW_COMMENTS_SUCCESS = 'space/REQUEST_GET_ALL_REVIEW_COMMENTS_SUCCESS',
  REQUEST_GET_ALL_REVIEW_COMMENTS_FAILURE = 'space/REQUEST_GET_ALL_REVIEW_COMMENTS_FAILURE',

  REQUEST_ADD_REVIEW_COMMENT = 'space/REQUEST_ADD_REVIEW_COMMENT',
  REQUEST_ADD_REVIEW_COMMENT_SUCCESS = 'space/REQUEST_ADD_REVIEW_COMMENT_SUCCESS',
  REQUEST_ADD_REVIEW_COMMENT_FAILURE = 'space/REQUEST_ADD_REVIEW_COMMENT_FAILURE',

  REQUEST_UPDATE_REVIEW_COMMENT = 'space/REQUEST_UPDATE_REVIEW_COMMENT',
  REQUEST_UPDATE_REVIEW_COMMENT_SUCCESS = 'space/REQUEST_UPDATE_REVIEW_COMMENT_SUCCESS',
  REQUEST_UPDATE_REVIEW_COMMENT_FAILURE = 'space/REQUEST_UPDATE_REVIEW_COMMENT_FAILURE',

  REQUEST_DELETE_REVIEW_COMMENT = 'space/REQUEST_DELETE_REVIEW_COMMENT',
  REQUEST_DELETE_REVIEW_COMMENT_SUCCESS = 'space/REQUEST_DELETE_REVIEW_COMMENT_SUCCESS',
  REQUEST_DELETE_REVIEW_COMMENT_FAILURE = 'space/REQUEST_DELETE_REVIEW_COMMENT_FAILURE',

  REQUEST_ADD_QUOTE = 'space/REQUEST_ADD_QUOTE',
  REQUEST_ADD_QUOTE_SUCCESS = 'space/REQUEST_ADD_QUOTE_SUCCESS',
  REQUEST_ADD_QUOTE_FAILURE = 'space/REQUEST_ADD_QUOTE_FAILURE',

  REQUEST_UPDATE_QUOTE = 'space/REQUEST_UPDATE_QUOTE',
  REQUEST_UPDATE_QUOTE_SUCCESS = 'space/REQUEST_UPDATE_QUOTE_SUCCESS',
  REQUEST_UPDATE_QUOTE_FAILURE = 'space/REQUEST_UPDATE_QUOTE_FAILURE',

  REQUEST_DELETE_QUOTE = 'space/REQUEST_DELETE_QUOTE',
  REQUEST_DELETE_QUOTE_SUCCESS = 'space/REQUEST_DELETE_QUOTE_SUCCESS',
  REQUEST_DELETE_QUOTE_FAILURE = 'space/REQUEST_DELETE_QUOTE_FAILURE',

  REQUEST_GET_ALL_QUOTE_COMMENTS = 'space/REQUEST_GET_ALL_QUOTE_COMMENTS',
  REQUEST_GET_ALL_QUOTE_COMMENTS_SUCCESS = 'space/REQUEST_GET_ALL_QUOTE_COMMENTS_SUCCESS',
  REQUEST_GET_ALL_QUOTE_COMMENTS_FAILURE = 'space/REQUEST_GET_ALL_QUOTE_COMMENTS_FAILURE',

  REQUEST_ADD_QUOTE_COMMENT = 'space/REQUEST_ADD_QUOTE_COMMENT',
  REQUEST_ADD_QUOTE_COMMENT_SUCCESS = 'space/REQUEST_ADD_QUOTE_COMMENT_SUCCESS',
  REQUEST_ADD_QUOTE_COMMENT_FAILURE = 'space/REQUEST_ADD_QUOTE_COMMENT_FAILURE',

  REQUEST_UPDATE_QUOTE_COMMENT = 'space/REQUEST_UPDATE_QUOTE_COMMENT',
  REQUEST_UPDATE_QUOTE_COMMENT_SUCCESS = 'space/REQUEST_UPDATE_QUOTE_COMMENT_SUCCESS',
  REQUEST_UPDATE_QUOTE_COMMENT_FAILURE = 'space/REQUEST_UPDATE_QUOTE_COMMENT_FAILURE',

  REQUEST_DELETE_QUOTE_COMMENT = 'space/REQUEST_DELETE_QUOTE_COMMENT',
  REQUEST_DELETE_QUOTE_COMMENT_SUCCESS = 'space/REQUEST_DELETE_QUOTE_COMMENT_SUCCESS',
  REQUEST_DELETE_QUOTE_COMMENT_FAILURE = 'space/REQUEST_DELETE_QUOTE_COMMENT_FAILURE',
}

export default ActionTypes;
