enum ActionTypes {
  REQUEST_GET_SALON = 'salon/REQUEST_GET_SALON',
  REQUEST_GET_SALON_SUCCESS = 'salon/REQUEST_GET_SALON_SUCCESS',
  REQUEST_GET_SALON_FAILURE = 'salon/REQUEST_GET_SALON_FAILURE',

  REQUEST_ADD_SALON = 'salon/REQUEST_ADD_SALON',
  REQUEST_ADD_SALON_SUCCESS = 'salon/REQUEST_ADD_SALON_SUCCESS',
  REQUEST_ADD_SALON_FAILURE = 'salon/REQUEST_ADD_SALON_FAILURE',

  REQUEST_UPDATE_SALON = 'salon/REQUEST_UPDATE_SALON',
  REQUEST_UPDATE_SALON_SUCCESS = 'salon/REQUEST_UPDATE_SALON_SUCCESS',
  REQUEST_UPDATE_SALON_FAILURE = 'salon/REQUEST_UPDATE_SALON_FAILURE',

  REQUEST_DELETE_SALON = 'salon/REQUEST_DELETE_SALON',
  REQUEST_DELETE_SALON_SUCCESS = 'salon/REQUEST_DELETE_SALON_SUCCESS',
  REQUEST_DELETE_SALON_FAILURE = 'salon/REQUEST_DELETE_SALON_FAILURE',

  REQUEST_GET_BOOK = 'salon/REQUEST_GET_BOOK',
  REQUEST_GET_BOOK_SUCCESS = 'salon/REQUEST_GET_BOOK_SUCCESS',
  REQUEST_GET_BOOK_FAILURE = 'salon/REQUEST_GET_BOOK_FAILURE',

  REQUEST_ADD_BOOK = 'salon/REQUEST_ADD_BOOK',
  REQUEST_ADD_BOOK_SUCCESS = 'salon/REQUEST_ADD_BOOK_SUCCESS',
  REQUEST_ADD_BOOK_FAILURE = 'salon/REQUEST_ADD_BOOK_FAILURE',

  REQUEST_DELETE_BOOK = 'salon/REQUEST_DELETE_BOOK',
  REQUEST_DELETE_BOOK_SUCCESS = 'salon/REQUEST_DELETE_BOOK_SUCCESS',
  REQUEST_DELETE_BOOK_FAILURE = 'salon/REQUEST_DELETE_BOOK_FAILURE',

  REQUEST_ADD_REVIEW = 'salon/REQUEST_ADD_REVIEW',
  REQUEST_ADD_REVIEW_SUCCESS = 'salon/REQUEST_ADD_REVIEW_SUCCESS',
  REQUEST_ADD_REVIEW_FAILURE = 'salon/REQUEST_ADD_REVIEW_FAILURE',

  REQUEST_UPDATE_REVIEW = 'salon/REQUEST_UPDATE_REVIEW',
  REQUEST_UPDATE_REVIEW_SUCCESS = 'salon/REQUEST_UPDATE_REVIEW_SUCCESS',
  REQUEST_UPDATE_REVIEW_FAILURE = 'salon/REQUEST_UPDATE_REVIEW_FAILURE',

  REQUEST_DELETE_REVIEW = 'salon/REQUEST_DELETE_REVIEW',
  REQUEST_DELETE_REVIEW_SUCCESS = 'salon/REQUEST_DELETE_REVIEW_SUCCESS',
  REQUEST_DELETE_REVIEW_FAILURE = 'salon/REQUEST_DELETE_REVIEW_FAILURE',

  REQUEST_GET_ALL_REVIEW_COMMENTS = 'salon/REQUEST_GET_ALL_REVIEW_COMMENTS',
  REQUEST_GET_ALL_REVIEW_COMMENTS_SUCCESS = 'salon/REQUEST_GET_ALL_REVIEW_COMMENTS_SUCCESS',
  REQUEST_GET_ALL_REVIEW_COMMENTS_FAILURE = 'salon/REQUEST_GET_ALL_REVIEW_COMMENTS_FAILURE',

  REQUEST_ADD_REVIEW_COMMENT = 'salon/REQUEST_ADD_REVIEW_COMMENT',
  REQUEST_ADD_REVIEW_COMMENT_SUCCESS = 'salon/REQUEST_ADD_REVIEW_COMMENT_SUCCESS',
  REQUEST_ADD_REVIEW_COMMENT_FAILURE = 'salon/REQUEST_ADD_REVIEW_COMMENT_FAILURE',

  REQUEST_UPDATE_REVIEW_COMMENT = 'salon/REQUEST_UPDATE_REVIEW_COMMENT',
  REQUEST_UPDATE_REVIEW_COMMENT_SUCCESS = 'salon/REQUEST_UPDATE_REVIEW_COMMENT_SUCCESS',
  REQUEST_UPDATE_REVIEW_COMMENT_FAILURE = 'salon/REQUEST_UPDATE_REVIEW_COMMENT_FAILURE',

  REQUEST_DELETE_REVIEW_COMMENT = 'salon/REQUEST_DELETE_REVIEW_COMMENT',
  REQUEST_DELETE_REVIEW_COMMENT_SUCCESS = 'salon/REQUEST_DELETE_REVIEW_COMMENT_SUCCESS',
  REQUEST_DELETE_REVIEW_COMMENT_FAILURE = 'salon/REQUEST_DELETE_REVIEW_COMMENT_FAILURE',

  REQUEST_ADD_QUOTE = 'salon/REQUEST_ADD_QUOTE',
  REQUEST_ADD_QUOTE_SUCCESS = 'salon/REQUEST_ADD_QUOTE_SUCCESS',
  REQUEST_ADD_QUOTE_FAILURE = 'salon/REQUEST_ADD_QUOTE_FAILURE',

  REQUEST_UPDATE_QUOTE = 'salon/REQUEST_UPDATE_QUOTE',
  REQUEST_UPDATE_QUOTE_SUCCESS = 'salon/REQUEST_UPDATE_QUOTE_SUCCESS',
  REQUEST_UPDATE_QUOTE_FAILURE = 'salon/REQUEST_UPDATE_QUOTE_FAILURE',

  REQUEST_DELETE_QUOTE = 'salon/REQUEST_DELETE_QUOTE',
  REQUEST_DELETE_QUOTE_SUCCESS = 'salon/REQUEST_DELETE_QUOTE_SUCCESS',
  REQUEST_DELETE_QUOTE_FAILURE = 'salon/REQUEST_DELETE_QUOTE_FAILURE',

  REQUEST_GET_ALL_QUOTE_COMMENTS = 'salon/REQUEST_GET_ALL_QUOTE_COMMENTS',
  REQUEST_GET_ALL_QUOTE_COMMENTS_SUCCESS = 'salon/REQUEST_GET_ALL_QUOTE_COMMENTS_SUCCESS',
  REQUEST_GET_ALL_QUOTE_COMMENTS_FAILURE = 'salon/REQUEST_GET_ALL_QUOTE_COMMENTS_FAILURE',

  REQUEST_ADD_QUOTE_COMMENT = 'salon/REQUEST_ADD_QUOTE_COMMENT',
  REQUEST_ADD_QUOTE_COMMENT_SUCCESS = 'salon/REQUEST_ADD_QUOTE_COMMENT_SUCCESS',
  REQUEST_ADD_QUOTE_COMMENT_FAILURE = 'salon/REQUEST_ADD_QUOTE_COMMENT_FAILURE',

  REQUEST_UPDATE_QUOTE_COMMENT = 'salon/REQUEST_UPDATE_QUOTE_COMMENT',
  REQUEST_UPDATE_QUOTE_COMMENT_SUCCESS = 'salon/REQUEST_UPDATE_QUOTE_COMMENT_SUCCESS',
  REQUEST_UPDATE_QUOTE_COMMENT_FAILURE = 'salon/REQUEST_UPDATE_QUOTE_COMMENT_FAILURE',

  REQUEST_DELETE_QUOTE_COMMENT = 'salon/REQUEST_DELETE_QUOTE_COMMENT',
  REQUEST_DELETE_QUOTE_COMMENT_SUCCESS = 'salon/REQUEST_DELETE_QUOTE_COMMENT_SUCCESS',
  REQUEST_DELETE_QUOTE_COMMENT_FAILURE = 'salon/REQUEST_DELETE_QUOTE_COMMENT_FAILURE',
}

export default ActionTypes;
