enum ActionTypes {
  REQUEST_GET_GET_ALL_REVIEWS = 'user/REQUEST_GET_GET_ALL_REVIEWS',
  REQUEST_GET_GET_ALL_REVIEWS_SUCCESS = 'user/REQUEST_GET_GET_ALL_REVIEWS_SUCCESS',
  REQUEST_GET_GET_ALL_REVIEWS_FAILURE = 'user/REQUEST_GET_GET_ALL_REVIEWS_FAILURE',

  REQUEST_GET_GET_ALL_QUOTES = 'user/REQUEST_GET_GET_ALL_QUOTES',
  REQUEST_GET_GET_ALL_QUOTES_SUCCESS = 'user/REQUEST_GET_GET_ALL_QUOTES_SUCCESS',
  REQUEST_GET_GET_ALL_QUOTES_FAILURE = 'user/REQUEST_GET_GET_ALL_QUOTES_FAILURE',
}

export default ActionTypes;
