enum ActionTypes {
  REQUEST_SIGN_UP = 'user/REQUEST_SIGN_UP',
  REQUEST_SIGN_UP_SUCCESS = 'user/REQUEST_SIGN_UP_SUCCESS',
  REQUEST_SIGN_UP_FAILURE = 'user/REQUEST_SIGN_UP_FAILURE',

  REQUEST_SIGN_IN = 'user/REQUEST_SIGN_IN',
  REQUEST_SIGN_IN_SUCCESS = 'user/REQUEST_SIGN_IN_SUCCESS',
  REQUEST_SIGN_IN_FAILURE = 'user/REQUEST_SIGN_IN_FAILURE',

  REQUEST_GET_CURRENT_USER = 'user/REQUEST_GET_CURRENT_USER',
  REQUEST_GET_CURRENT_USER_SUCCESS = 'user/REQUEST_GET_CURRENT_USER_SUCCESS',
  REQUEST_GET_CURRENT_USER_FAILURE = 'user/REQUEST_GET_CURRENT_USER_FAILURE',
}

export default ActionTypes;
